version: '3.8'
services:
  web:
    image: networkapp:1.0
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/app/djangoapp/staticfiles  # Mount staticfiles volume
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.200
      - DJANGO_TRUSTED_ORIGIN=http://localhost,192.168.1.200    
           

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount nginx configuration file
      - staticfiles:/app/staticfiles  # Mount staticfiles volume 
    depends_on:
      - web

volumes:
  staticfiles: