---
# tasks file for interfaces
- name: set interface up
  cisco.ios.ios_interfaces:
    config:
    - name: "{{interfaces}}"
      description: Configured and Merged by Ansible Network
      enabled: "{{enable_state}}"