# Generated by Django 5.1.2 on 2025-02-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqename', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
    ]
