---
- name: set interface up
  cisco.ios.ios_interfaces:
    config:
    - name: "{{interfaces}}"
      description: Configured and Merged by Ansible Network
      enabled: true

- name: Set interface ipv4
  cisco.ios.ios_l3_interfaces:
    config:
    - name: "{{interfaces}}"
      ipv4:
        - address: "{{ipv4}}"

