---
- name: Merge provided configuration with device configuration
  cisco.ios.ios_interfaces:
    config:
    - name: GigabitEthernet{{interfaces}}
      description: Configured and Merged by Ansible Network
      enabled: true

- name: Merge provided configuration with device configuration
  cisco.ios.ios_l3_interfaces:
    config:
    - name: GigabitEthernet{{interfaces}}
      ipv4:
        - address: "{{ipv4}}"

