---
- name: Gather information about the Cisco router
  hosts: all
  gather_facts: false

  tasks:
   - name: Ping devices
     cisco.ios.ios_ping:
       dest: "{{ ansible_host }}"
   - name: Gather only the config and default facts
     ios_facts:
      gather_subset: all
     register: current_users


   - name: Save facts to a JSON file
     copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "./temp/router_facts_{{ inventory_hostname }}.json"
