- name: Configure IOS devices
  hosts: routers
  gather_facts: false
  roles:
    - { role: hostname  , when: "'hostname' in selected_roles"        }
    - { role: banner    , when: "'banner' in selected_roles"          }
    - { role: ip_config , when: "'ip_config' in selected_roles"       }
    - { role: interfaces, when: "'interface-state' in selected_roles" }
    - { role: ospf      , when: "'ospf' in selected_roles"            }